name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: make test
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.PAT }}
          allow-initial-development-versions: true
          changelog-file: CHANGELOG.md
          update-file: package.json
          changelog-generator-opt: "emojis=true"
          force-bump-patch-version: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(ci): commit changes from go-semantic-release'
          file_pattern: CHANGELOG.md package.json
